name: Java CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify -Dgpg.skip
      - run: mkdir snapshots && cp target/*.jar snapshots
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: snapshots
